name: main workflow
on: [push]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: build with maven
        run: |
          mvn package
          ls -la
        working-directory: back
      
      
      
