name: main workflow
on: [push]

jobs:
  build-backend:
    defaults:
      run:
        working-directory: back
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: build with maven
        run: mvn package
      - uses: actions/upload-artifact@v4
        with:
          name: bobapp-backend-artifact
          path: back/target
      - uses: actions/upload-artifact@v4
        with:
          name: bobapp-backend-artifact
          path: target

      - name: Generate report
        run: |
          mvn jacoco:report
          ls -la target/site/jacoco

      - name: Backend code coverage
        uses: PavanMudigonda/jacoco-reporter@v4.9
        with:
          coverage_results_path: ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml
          coverage_report_name: Bobapp test coverage
          coverage_report_title: Bobapp test coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  push-backend:
    defaults:
      run:
        working-directory: back
    runs-on: ubuntu-latest
    needs: [build-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Mise en place de Buildx
        uses: docker/setup-buildx-action@v3
        
      - uses: actions/download-artifact@v4
        with:
          name: bobapp-backend-artifact
          path: back/target
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - run: ls -la
      
      - name: Push image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: kulturman/bobapp-backend:latest
