name: main workflow
on: [push]

jobs:
  build-backend:
    defaults:
      run:
        working-directory: back
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: build with maven
        run: mvn package
      - uses: actions/upload-artifact@v4
        with:
          name: bobapp-backend-artifact
          path: target

  push-backend:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    needs: [build-backend]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bobapp-backend-artifact
          path: target
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: ls -la
