name: main workflow
on: [push]

jobs:
  build-backend:
    defaults:
      run:
        working-directory: back
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: build with maven
        run: mvn package
          
      - name: Generate report
        run: |
          mvn jacoco:report
          ls -la target/site/jacoco
          
      - name: Backend code coverage
        uses: PavanMudigonda/jacoco-reporter@v4.9
        with:
          coverage_results_path: ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml
          coverage_report_name: Bobapp test coverage
          coverage_report_title: Bobapp test coverage
          
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
