name: main workflow
on: [push]

jobs:
  test-frontend:
    defaults:
      run:
        working-directory: front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - run: npm i -g @angular/cli
      - run: npm i --cache .npm
      - run: ng test --no-watch --code-coverage
      
