name: main workflow
on: [push]

jobs:
  test-frontend:
    defaults:
      run:
        working-directory: front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm i -g @angular/cli
      - run: npm i --cache .npm
      - run: ng test --browsers ChromeHeadless --no-watch --code-coverage
      - uses: actions/cache@v3
        with:
          key: ${{runner.os}}-${{hashFiles('./front/package.json')}}
          path: .npm
      - uses: actions/upload-artifact@v4
        with:
          name: bobapp-frontend-code-coverage
          path: coverage

  push-images:
    strategy:
      matrix:
        stack: [front, back]
    runs-on: ubuntu-latest
    needs: [test-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Mise en place de Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Push images with tags
        uses: docker/build-push-action@v5
        with:
          context: ./${{matrix.stack}}
          file: ./${{matrix.stack}}/Dockerfile
          push: true
          tags: kulturman/bobapp-${{matrix.stack}}:${{github.sha}}

      - name: Push images with latest
        uses: docker/build-push-action@v5
        with:
          context: ./${{matrix.stack}}
          file: ./${{matrix.stack}}/Dockerfile
          push: true
          tags: kulturman/bobapp-${{matrix.stack}}:latest
        
