name: main workflow
on: [push]

jobs:
  build-backend:
    defaults:
      run:
        working-directory: back
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: build with maven
        run: mvn package
          
      - name: Generate report
        run: |
          mvn jacoco:report
          ls -la target/site/jacoco
          
      - name: Backend code coverage
        uses: PavanMudigonda/jacoco-reporter@v4.9
        with:
          coverage_results_path: ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml
          coverage_report_name: Bobapp test coverage
          coverage_report_title: Bobapp test coverage
          
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=kulturman_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
      
