name: main workflow
on: [push]

jobs:
  build-backend:
    defaults:
      run:
        working-directory: back
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: build with maven
        run: mvn package
      - uses: actions/upload-artifact@v4
        with:
          name: bobapp-backend-artifact
          path: back/target

  push-backend:
    defaults:
      run:
        working-directory: back
    runs-on: ubuntu-latest
    needs: [build-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Mise en place de Buildx
        uses: docker/setup-buildx-action@v3
        
      - uses: actions/download-artifact@v4
        with:
          name: bobapp-backend-artifact
          path: back/target
          
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - run: ls -la
      
      - name: Push image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: latest
